### PR TITLE
Implemented light and dark theme.

### PR DESCRIPTION
**Pull request by ahaandesai27**
Implemented light and dark theme by applying a context 'darkMode : boolean' across all components. Styles are applied based on a ternary check. For example : const gridStyles = darkMode ? 'grid-container' : 'grid-container grid-container-light' . The default style is dark.

Dashboard:
image
image

Coin page:
image
image

### CODE REVIEW

**Comment by AkashJana18** [comment]
- @ahaandesai27 Create the changes in new branch (not directly in main branch)
- Refer the [figma design](https://www.figma.com/design/J1qMb6OQJWumOTLZtTB081/Cryptack?node-id=0-1&node-type=CANVAS&t=uWViQIgys5fXUQwq-0) for light theme so that the UI/UX is maintained
- Also use toggle button from mui.

**Comment by ahaandesai27** [comment]
> - @ahaandesai27 Create the changes in new branch (not directly in main branch)
> - Refer the [figma design](https://www.figma.com/design/J1qMb6OQJWumOTLZtTB081/Cryptack?node-id=0-1&node-type=CANVAS&t=uWViQIgys5fXUQwq-0) for light theme so that the UI/UX is maintained
> - Also use toggle button from mui. 

I'll work on the changes, but I've already created the changes in my own branch 'ahaan-desai-theme'. Could you please clarify what exactly did you mean by point 1?

**Comment by AkashJana18** [comment]
> > * @ahaandesai27 Create the changes in new branch (not directly in main branch)
> > * Refer the [figma design](https://www.figma.com/design/J1qMb6OQJWumOTLZtTB081/Cryptack?node-id=0-1&node-type=CANVAS&t=uWViQIgys5fXUQwq-0) for light theme so that the UI/UX is maintained
> > * Also use toggle button from mui.
> 
> I'll work on the changes, but I've already created the changes in my own branch 'ahaan-desai-theme'. Could you please clarify what exactly did you mean by point 1?
My apologies for the misunderstanding. Just make the further changes

**Review by AkashJana18 — CHANGES_REQUESTED** [review]
The header text on home page had a hover effect which is lost now. Please fix that in both the themes.
Also the share button should be transparent. 
The chart on compare page is still dark. 
Add the theme toggle button on mobile responsive menu too.
image
image
image

**Comment by ahaandesai27** [comment]
Noted, will work on it tomorrow.

**Comment by ahaandesai27** [comment]
Good evening, I've completed most of the changes but I was unable to change the theme for the responsive sidebar as it is a native MUI component.

**Comment by AkashJana18** [comment]
Yes except that everything looks fine, I will proceed further with merging the PR. Thank you for the contribution.

**Review by AkashJana18 — APPROVED** [review]

**Pull request merged**
